language: ruby

before_install:
  - curl -L https://raw.githubusercontent.com/krlmlr/texlive-squashfs/master/out/texlive.tar.xz | tar xJC ~

install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH

script:
  - pdflatex -interaction=nonstopmode book.tex

deploy:
  provider: releases
  api_key:
    secure: UFJLRu6WMLjtAiJfJrdTyJ7fxIXiSy3low8u55URmmHLlemgF94p/LwBSLQj4y0vjOzyJOdoEcX7oiLlW1VFVJLvAcnfkA9z09+olvfRmydzVgpFC/4LXnAt+bJPheQy8VAupiXiv70LebnqBOOrGipdAibO5ZVxwvhmuLri8/z4ntHwYY6RUliqp6mswyaEwASoCmwjqsIXiMfSEZ0hXGzrB21qhfIEGJ8a41dNFmxKp0hLcB29XVFmmGpVEqRrmAoEzO+JPp8Df8o1nSa/Hl5zlxB0zi0xxT9QQYBzd43+4ItmBsqEbG4aJmoAb7s5yvDpSnvSiVB2oJrtnlr5DFNriMYpRSJIoDCx+WhlVPhN+gZwru8ejOP9rUCdV+N9dldIfRXhIsEkQ9Phi4qkbT7kFPT6DVhjymp+p4CLOq/FFVdfRxAQ5J8t6xd6z1r3k7ry9BV5HyLd0qkj4G1WCMDIRSWutuBhTWJOKqpiumNpaJDB1TqfS7EljZYidj36Y9QxFxapLeevuTtV/iND0E1Kfp2YYoT6ULGA1vTuOIK3+Q0Vl96+GLN0l+/FJpoPTLHyr2njVnGiYqi8oOBKQvYj1Mjc6Nv5PKI9f3RSLYxCYxxU1Tg9uSj2xi1otfB5UyEvr6Gtmcr7Co5ONX7hR3D62ZsJUyYc+S6XlAoQBkA=
  file: book.pdf
  on:
    repo: mafagafogigante/formulas
